#!/bin/sh
test -n "$1" || echo "usage: platex2pdf [tex-file]"
test -n "$1" || exit 1 # 引数が無ければ syntax を表示して終了

if [ "$1" = "clean" ]; then
    rm -rf build
    echo "rm -rf build"
    for fname in *.tex; do
        rm -f ${fname%.tex}.pdf
        echo "rm -f ${fname%.tex}.pdf"
    done
    exit 0
fi

TEX=$*
DVI=`/usr/bin/basename "$TEX" ".tex"`
THECODE=`nkf -g "$TEX"`
case $THECODE in # nkf が返す文字コードにあわせる
    UTF-8) KANJI="-kanji=utf8";;
    EUC-JP) KANJI="-kanji=euc";;
    Shift-JIS) KANJI="kanji=sjis";;
    ISO-2022-JP) KANJI="-kanji=jis";;
esac
PLATEX="platex"
OUTDIR="build"
PLATEX_FLAGS="-output-directory=$OUTDIR"
CLASS=`sed -n '/documentclass/p' $* | sed '/%.*documentclass/d' | sed -n '1p'`
case $CLASS in
    *{u*) PLATEX="uplatex";;
esac
mkdir -p $OUTDIR
echo gjeogjeo
echo $DVI
$PLATEX $KANJI $PLATEX_FLAGS $TEX  # platex コマンドの発行
dvipdfmx $OUTDIR/$DVI # dvipdfmx コマンドの発行
evince  "$DVI.pdf" &
